### ISSUE TITLE
Concat links

### ISSUE THREAD

**Issue by YouMinTW** [benawad/apollo-server-react-file-upload#6]
Hi Ben
Thanks for so many tutorial!
I have created an Apollo Client with JWT  from your video https://www.youtube.com/watch?v=25GS0MLT8JU

And I would like to use this upload link, but I'm not sure how to compose links with this and I couldn't find some related practice.
May I know that is this uploadLinks possible to concat links like
```
const uploadLink = createUploadLink({ uri: MY_GRAPHQL_ENDPOINT })
const client = new ApolloClient({
    link: ApolloLink.from([
      new TokenRefreshLink({
        ...),
      requestLink,
      uploadLink
    ]),
    cache: new InMemoryCache()
  })

  return client
}
```

It seems not works as I expected.
I'm new to React and GraphQL so I'm not sure is it proper to inquire this issue here.
If it's not,please tell me and I will delete it immediately.
I appreciate your kindness!
Thank you

**Comment by benawad** [comment]
I think that should work, upload link replaces http link

**Comment by YouMinTW** [comment]
Thaks a lot, I sloved this issue via https://github.com/graphql-python/graphene-django/issues/404
My request body was included query, and I didn't handle the formdata at my backend so the resolver couldn't recognize query.
